spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: tracker_maintenance_service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB   # tối đa 10 file × 10MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 300 # in second
  refreshable-duration: 1800 # in second


cloudflare:
  r2:
    endpoint: https://35c1e2b268d20d1a9ea899121b159d74.r2.cloudflarestorage.com/tracker-maintennance
    publicUrl: https://pub-d6fe58f1fd4a4bddaf8f4f390153b02a.r2.dev
    bucketName: tracker-maintennance
    accessKey: ${APP_R2_ACCESS_KEY_ID}
    secretKey: ${APP_R2_SECRET_ACCESS_KEY}
    region: auto